export const AvatarPlaceholderLink = "https://media-exp1.licdn.com/dms/image/C5103AQGkoPPNt57f_A/profile-displayphoto-shrink_200_200/0/1586686364183?e=1616025600&v=beta&t=tx8Rr5dugU-uQaJixN7G9OKmRAEXX5Ng2KTg3LNPOTE"
export const MyIGImageLink = "https://media-exp1.licdn.com/dms/image/C5103AQGkoPPNt57f_A/profile-displayphoto-shrink_200_200/0/1586686364183?e=1616025600&v=beta&t=tx8Rr5dugU-uQaJixN7G9OKmRAEXX5Ng2KTg3LNPOTE"
export const LargeAvatarLink = "https://media-exp1.licdn.com/dms/image/C5103AQGkoPPNt57f_A/profile-displayphoto-shrink_200_200/0/1586686364183?e=1616025600&v=beta&t=tx8Rr5dugU-uQaJixN7G9OKmRAEXX5Ng2KTg3LNPOTE"

export const NAV_POST_ID = 0;
export const NAV_IGTV_ID = 1;
export const NAV_TAGGED_ID = 2;

// seconds
export const TOP_PROGRESSBAR_TIME = 0.8;

export const TEMP_RESULT_DATA = [
  {
    "userAccount": "henry32144",
    "imageLink": MyIGImageLink,
    "infoTitle": "henry32144",
    "infoText": "承翰 吳",
    "isVerified": false,
  },
  {
    "userAccount": "tempAccount2",
    "imageLink": undefined,
    "infoTitle": "tempAccount2",
    "infoText": "Temp Account 2",
    "isVerified": false,
  },
  {
    "userAccount": "tempAccount3",
    "imageLink": undefined,
    "infoTitle": "tempAccount3",
    "infoText": "Temp Account 3",
    "isVerified": true,
  },
  {
    "userAccount": "tempAccount4",
    "imageLink": undefined,
    "infoTitle": "tempAccount4",
    "infoText": "Temp Account 4",
    "isVerified": false,
  },
  {
    "userAccount": "tempAccount5",
    "imageLink": undefined,
    "infoTitle": "tempAccount5",
    "infoText": "Temp Account 5",
    "isVerified": true,
  },
  {
    "userAccount": "tempAccount6",
    "imageLink": undefined,
    "infoTitle": "tempAccount6",
    "infoText": "Temp Account 6",
    "isVerified": false,
  },
];

export const TEMP_POSTS = [
  {
    "key": 0,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BWFRJNjgsGD/",
    "src": "./placeholder.jpg",
    "likeNumber": "48",
    "commentNumber": "6",
  },
  {
    "key": 1,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BU5dQo5g5jU/",
    "src": "./placeholder.jpg",
    "likeNumber": "48",
    "commentNumber": "6",
  },
  {
    "key": 2,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BUDpVLZgWAB/",
    "src": "./placeholder.jpg",
    "likeNumber": "35",
    "commentNumber": "4",
  },
  {
    "key": 3,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BTYwWacg-62/",
    "src": "./placeholder.jpg",
    "likeNumber": "27",
    "commentNumber": "4",
  },
  {
    "key": 4,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BS6L4lrgYF0/",
    "src": "./placeholder.jpg",
    "likeNumber": "60",
    "commentNumber": "6",
  },
  {
    "key": 5,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BSdM6aogsnB/",
    "src": "./placeholder.jpg",
    "likeNumber": "41",
    "commentNumber": "6",
  },
  {
    "key": 6,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BSDgKHpAmag/",
    "src": "./placeholder.jpg",
    "likeNumber": "31",
    "commentNumber": "NaN",
  },
  {
    "key": 7,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BQ5dxoxA79f/",
    "src": "./placeholder.jpg",
    "likeNumber": "67",
    "commentNumber": "23",
  },
  {
    "key": 8,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BQu39GjgNzZ/",
    "src": "./placeholder.jpg",
    "likeNumber": "40",
    "commentNumber": "1",
  },
  {
    "key": 9,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BQoWeoKAn4S/",
    "src": "./placeholder.jpg",
    "likeNumber": "35",
    "commentNumber": "5",
  },
  {
    "key": 10,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BPesKwMFRAB/",
    "src": "./placeholder.jpg",
    "likeNumber": "39",
    "commentNumber": "3",
  },
  {
    "key": 11,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BPaOwOBFCZ5/",
    "src": "./placeholder.jpg",
    "likeNumber": "35",
    "commentNumber": "2",
  },
  {
    "key": 12,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BIFO-vHA_2u/",
    "src": "./placeholder.jpg",
    "likeNumber": "92",
    "commentNumber": "14",
  },
  {
    "key": 13,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/BFJX_meOYBT/",
    "src": "./placeholder.jpg",
    "likeNumber": "75",
    "commentNumber": "24",
  },
  {
    "key": 14,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/-3yci7uYDE/",
    "src": "./placeholder.jpg",
    "likeNumber": "75",
    "commentNumber": "24",
  },
  {
    "key": 15,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/7foYgGuYCw/",
    "src": "./placeholder.jpg",
    "likeNumber": "76",
    "commentNumber": "12",
  },
  {
    "key": 16,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/3W-drMOYHR/",
    "src": "./placeholder.jpg",
    "likeNumber": "66",
    "commentNumber": "17",
  },
  {
    "key": 17,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/3UWp5eOYD-/",
    "src": "./placeholder.jpg",
    "likeNumber": "29",
    "commentNumber": "4",
  },
  {
    "key": 18,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/3R7J3sOYLq/",
    "src": "./placeholder.jpg",
    "likeNumber": "22",
    "commentNumber": "1",
  },
  {
    "key": 19,
    "imgAlt": "A Photo",
    "href": "https://www.instagram.com/p/3QzUYNuYLA/",
    "src": "./placeholder.jpg",
    "likeNumber": "24",
    "commentNumber": "9",
  },
]